name: Manual Workflow
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Release, Debug]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild /m /p:Platform=x86 /p:Configuration=${{matrix.build_configuration}} TM.sln

    - uses: actions/upload-artifact@master
      with:
        name: TMProject_${{matrix.build_configuration}}
        path: ${{matrix.build_configuration}}/TMProject.exe
